### ISSUE TITLE
New Design for Quran app 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [quran/quran-ios#165]
@mohamede1945 Assalmau Alaikum, I was wondering if you wanted to work together and redesign the Quran app with the following design, inshallah I would also be able to write automation scripts in order to test the app.

|image| image|
|------|-------|
|![a01](https://cloud.githubusercontent.com/assets/7900956/26530908/875c754e-43d6-11e7-9301-bd9232e57c40.png)|![desktop hd](https://cloud.githubusercontent.com/assets/7900956/26530907/875a1308-43d6-11e7-92c2-c4d9df4e9bd0.png)|
|![desktop hd 2x](https://cloud.githubusercontent.com/assets/7900956/26530910/87608fc6-43d6-11e7-8004-1dcc88ccd64e.png)|![desktop hd2](https://cloud.githubusercontent.com/assets/7900956/26530909/87605b46-43d6-11e7-8346-05eea7714bf3.png)|

**Comment by mohamede1945** [comment]
@Ashraf-Ali-aa We alikom elsalam! Thanks again for your suggestions!

While that design looks really beautiful and I appreciate so much your efforts here, I wouldn't go for a complete redesign of the app like that. The reason is that most of the reviews on the app store is saying that they like the current design. So, I don't want to surprise them with a totally different design. Another reason would be that the iOS app is a port of the [Android app](https://play.google.com/store/apps/details?id=com.quran.labs.androidquran&hl=en). Though, I would encourage small incremental useful changes to the current design. Also we will in the future support night theme, if you would like to help on it that would be great!

Jazak Allah khyran

**Comment by mohamede1945** [comment]
Thanks again for your suggestion and we would love to work with you on improving the current design if you would like.
