### ISSUE TITLE
Search By Ayah Number

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#180]
One request from App store review:
>it would be more lovely if you can add a new feature where we can search the whole Quran by the number of the surah and verse. E.g: 2:183

**Comment by abunur** [comment]
So rather than a search I think we are lacking something in the navigation from being able to jump to a particular ayah. But am not sure what the most intuitive way to implement such a feature would be...have to think about this one.  In one of the other Quran apps they implemented it such a way that it was often easy to accidentally jump to another ayah, making more of an annoyance than a benefit

**Comment by Abdullah076** [comment]
check jump to verses option in Quran Majeed app in iOS. their system is pretty good

**Comment by mohamede1945** [comment]
@abunur I totally agree that we need to think about a good way for jumping to verses, though we can still implement this simple enhancement. So, I will create a ticket for easily jumping to verses.

@Abdullah076 I will check it

**Comment by mohamede1945** [comment]
It seems Quran Majeed jump to Ayah feature is so similar to what the Android app is doing.

**Comment by Abdullah076** [comment]
brother they have two ways to jump to verses. check the other one (icon is present in the bottom part)
where you can filter by surah name/ number & verse number.

**Comment by mohamede1945** [comment]
That was the one I found which I believe very similar to what the Android is doing. Where is the other one?

**Comment by mohamede1945** [comment]
Fixed in https://github.com/quran/quran-ios/commit/e239788b0f43f89e36ec9127cd01971f18c3c23b
