### ISSUE TITLE
Surah select failure from Juz' 20

### ISSUE THREAD

**Issue by abdelouali** [quran/quran-ios#26]
If I press by example on Surah Al-Qasas. If see Surah An-Naml instead of Al-Qasas

**Comment by mohamede1945** [comment]
This one is a little bit argumental. Because I show the sura name for the
first ayah in the page. It will be a more problematic when we have more
than 1 sura for example in Juz' 30.

Also, I think if we check some hard copy mushaf have it the same at the top
they display the name of the sura for the first ayah.

Do you agree?

On Tuesday, May 31, 2016, Abdelouali Benkheil <notifications@github.com>
wrote:

> If I press by example on Surah Al-Qasas. If see Surah An-Naml instead of
> Al-Qasas
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/quran/quran-ios/issues/26>, or mute the thread
> <https://github.com/notifications/unsubscribe/AFZy2ht1Bd2YUqg_4oQN-Coqc-DFYNL3ks5qHCMhgaJpZM4IqdQr>
> .
>


-- 
Best Regards,
Mohamed Afifi

**Comment by abdelouali** [comment]
Yes I agree.

This issue can be closed :)
