### ISSUE TITLE
Include an annotation section

### ISSUE THREAD

**Issue by Tahfimul** [quran/quran-ios#322]
Assalamu Alaikum,

I am very pleased to see the progress you have made towards the up keep of this website by the grace of Allah Subahana Watalla. One feature which I will suggest is the addition of annotation of the Qur'an. There are many Khatibs and Scholars of Islam who strive to bring conversations of the verses of the Qur'an. I believe that these contributions should be compiled and made view able to users of this website so that we all can better understand the Qur'an. Of course, the integrity of the Khatibs and Scholars should be fact checked.

I encourage you check out this page as an example: https://genius.com/17944294

Jazakallah Kairun

**Comment by mohamede1945** [comment]
We alikom elsalam we rahmat Allah we baraktoh,

First thank you for opening a ticket with us. We are really very happy to see people would like to improve the app. I totally agree that's a great idea. I think having this would be very beneficial to all users and having social interaction in general in the app will encourage people to stay more, read more, understand better, and memorize more of the Quran. I will try to gather some ideas around social interaction and this definitely will be one of them and discuss them with the team and try to implement them inshaa'Allah.

**Comment by Tahfimul** [comment]
Assalamu Alaikum,

I want to thank you brothers for the revamping of Quran.com and introducing the "Tafsirs" and "Quran Reflect" applications. I am really impressed by the work on Quran Reflect. One major issue that I noticed and I believe should be of concern since we are dealing with قلم الله and كتاب الله is that there should be thorough fact checking of the user posting the information and the information they are posting; especially commentary of Ayahs of the Qur'An if not replies to the commentary and even consider disabling the replies to the commentary feature as a whole and keep the like button feature; because I believe this will prevent users of the service from receiving an improper view of the message of Allah if not distort its meaning. I absolutely support reflecting upon Ayahs in the Qur'An because it is a writing like no other; but that also means that we as Muslims have a responsibility to gather the reflections from credible sources so that there is validity and quality rationale in such reflection. To this end, I would like to refer you to some sources that you might consider reaching out to seek out credible استاد  and عالِمٌ :
 
See this link for the list of sources (You may have to authorize Draw.io application by diagrams.net to view the document in Google Drive): https://drive.google.com/file/d/1AIYGvwWVfQeswlE90sskbSnp3oB7NuXw/view?usp=sharing

Jazakallah Khairun

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakumAllah khairan for your message - so we don't run QuranReflect, but friends of ours do. our initial agreement with them was to link to only the shuyookh and students of knowledge feed, but i am not sure why that's not happening at the moment - i'll follow up with this in sha' Allah.
walsalam 3alaikum

**Comment by Tahfimul** [comment]
Assalamu Alaikum brother @ahmedre ,

Any update on this issue?

Jazakallah Khairun

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i did follow up with them and they assured me that the page we point to (specifically with the url parameter of `&feed=true` are only by either shuyookh or verified students of knowledge, and all these entries are specifically read and screened before being put on the site. on their site in general, however, anyone can add reflections, but these shouldn't show up when coming from quran.com itself.
walsalam 3alaiakum.

**Comment by Tahfimul** [comment]
Assalamu Alaikum,

I have followed the flow that is to happen from Quran.com to QuranReflect.com and I found that the reflections from random users are easily reachable and I myself was able to create a fake account to make a reflection on سورة 39 : الزمر and there is actually a box that says "Search and create posts by surah, ayah, and/or #topic" 

Here is a simple GIF that I created to show the flow:

<img src="https://media.giphy.com/media/c3TJRZG8QA9LXCxpoB/giphy.gif" width="800" height="400" />

I understand that their website in general allows this and Quran.com doesn't have any control over it and that is their decision, I don't want to get involved in, but I am referring to the aspect of QuranReflect that this project does have control over. Quran.com is a universal website that has much more visitors than QuranReflect, so we should definitely be aware as to the services being included to this wonderful website, again so we don't divert away from the message of Allah. May be QuranReflect team has to create an entirely different section to seclude this system, where no part of log in and sign up and "Search and create posts by surah, ayah, and/or #topic" are available as the ```&feed=true``` parameter seems ineffective at the moment for Quran.com to QuranReflect flow.

Jazakallah Khairun

**Comment by amerabbas** [comment]
Assalamu Alaikum wa Rahmatu Allah wa barakatuh brother @Tahfimul,

Jazak Allah Khair for starting this valuable thread. QuranReflect is pretty much a social annotation engine around the Quran, and our mission is to cultivate a culture of reflection upon the Quran.. enabling what you brought up at the top of this thread. We value your ideas and contributions and insha'Allah we will address some of them now and mitigate the rest very soon.

First, if you click on the Quran.com ayah link it will take you to URL with parameter feed=true which will only show verified content, contributors, and people signed in user follows. It will NOT show random posts. If you update search box and add more filters, it will retain this filter, however, as you may have noticed, when you click away, the feed=true flag drops, and this is something we already added and will deploy this week insha'Allah. So even if you click away from Ayah, you will still only see quality content by public figures, imams/scholars and seekers of knowledge. But please note that this is happening now in the quran.com link.

Second, I'd like to say that all posts are being reviews as soon or shortly after they are posted, EVEN if they do not show in the main feed (filtered) or Quran.com link (also filtered). So for example, the team brought your post to my attention this morning, and as soon as we see something inappropriate (in relation to what reflections are and are not) we would remove it.

Third, the discussion is ongoing, do we limit sharing reflections (not tafsir) only to people of knowledge or do we make it more accessible. If we err on side of safety, we continue with status quo of people feeling intimidated to reflect on the Quran and discuss with others, something that was transformative for me and many others and as we've seen by some users on QuranReflect (one user saying: "I never knew the Quran was this approachable"). But If we err on the side of openness, then we need to architect the experience, filters, and moderation so that we do not allow for any misinterpretation (which should not happen if it's just a reflection) that could harm people's understanding of the Quran. The good news is that in the current scale it is fully under control. But more importantly, I have personally surrounded myself with world renown scholars and shoyoukh who insisted on the important of this initiative, but also insist on making sure we do not cause any harm.

Based on your input, and other input we got over the past weeks and months, I have compiled all questions/concerns, and will do another round of validation with scholars specialized in Quran.

So stay tuned insha'Allah for:
1. Feature that keeps verification flag on even if you click away.
2. Input from scholars on the balance of benefit vs. harm of making Quranic reflections accessible to everyone.

That said, if the risk grows, we are ready to make contributions more restricted until a user gets verified, but we may keep that as a last line of defense because we truly feel the opportunity of eliminating intimidation and open doors for people to reflect openly far outweighs the risk.

Insha'Allah at the end of this discourse we would have all contributed to answering important questions that the rest of the ummah can benefit from when engaging the Holy book of Allah swt.

**Comment by mohamede1945** [comment]
Current direction of the app is to keep the text limited to Quran, translations and tafseers.

**Comment by Tahfimul** [comment]
Jazakallah for the hard work involved in driving the new vision. I hope to see the changes soon.

**Comment by Tahfimul** [comment]
ٱلسَّلَامُ عَلَيْكُمْ
@amerabbas and @mohamede1945 
As an extension to QuranReflect, can I now suggest a social media app? The reason for this suggestion is that we have seen time and time again social media sites censoring content related to Muslim issues. What if we can develop a social media site/application where there will be a safe space for Muslims to share their thoughts, pictures, videos, hashtags, appear on explorer page and etc? This social media application will ofcourse not be included in Quran.com but be a separate social media site. We will also need to find a way to publicize and promote the app to the muslim audiences around the world. Let me know your thoughts about this.
