### ISSUE TITLE
Bookmarking Quran Page

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#34]
- [x] Add the ability to bookmark a page and remove bookmarking of a page if bookmarked.
- [x] Label a bookmarked page with a different icon than not bookmarked one.

**Comment by mohamede1945** [comment]
I'm currently working on this feature.

**Comment by mohamede1945** [comment]
I will be using Realm for data persistence.

**Comment by ahmedre** [comment]
i like Realm (and use it in some apps) - i just have 2 things i want to point out:
1. Quran for Android still uses sqlite for storing databases, so we'll have to make the schemas remain the same, especially when we eventually do the sync with the Quran sync service that's being built now.
2. Realm by default tends to make it super easy to query Realm from the ui thread, which is a bad thing (especially since certain queries are, indeed, slow). Just something to keep in the back of your mind.

**Comment by mohamede1945** [comment]
After some discussion with @ahmedre we decided to use sqlite to be consistent with the Android.
