### ISSUE TITLE
Addition of possiblity of saving resources like recitor voice or translation on extern device

### ISSUE THREAD

**Issue by Qobustan** [quran/quran-ios#403]
IOS offers the ability to plug extern usb device in. It would be great if you would add support to save resources there.

**Comment by mohamede1945** [comment]
Hi @Qobustan, thanks for the feature request. It's unlikely we would support something like that because the app is not a file management app. The files the app downloads need special processing before displaying them to the user. For example translation text is a SQLite file and not a PDF. 

While users can use the Audio files as they are, but I would suggest users use other means to download the audio files from the many websites that offer them online.

Lastly, adding a feature has a maintenance cost to ensure it's always functioning in future app releases and iOS releases and I don't see such a feature to become widely used to justify such a cost.
