### ISSUE TITLE
Images from API?

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran-ios#67]
Just a thought:

On Quran.com, we used to use images instead of font but eventually decided font with the web is best. But since the size of the app is so large, thoughts about doing the same for the app? For example, we can render text and for those that have internet connection, it'd download the images and replace them with the text. Similar to what we do on Quran.com too. You can also load a few pages before and after, so not needing to download all the images for the whole Surah but where the user might scroll.

Thoughts?

**Comment by ahmedre** [comment]
so a few things:
1. after the recent changes, our release build is down to ~85mb right now. if we render with fonts (which we could), the fonts weigh in at about 65mb - that means we would save ~10-20mb. we'd get other benefits (nicer translation view) and we'd lose some things too (ease of switching to a different set of pages), so it's a tradeoff - but if we do this, app size isn't the reason anymore.

2. images from the API is a good idea for "auxiliary" parts of the app (non-core functionality - i say this because lots of people download this app specifically to be able to read the old madani mus7af which they're used to) - but if the people using the iOS app are anything like the Android ones, internet availability (connection speed, cost, etc) are all major issues that are better solved with a one time cost than an incremental one. if 80+% of the people using the app are in the US/Europe/Australia, then I could agree with this, but if not, we'll end up frustrating people overall.

**Comment by mmahalwy** [comment]
@ahmedre I agree with what you're saying. But shouldn't we have data to back this up? For example, we uncovered that a huge portion of Quranicaudio users are on mobile. I would have not known. Makes me question what could we have done better to not worry about web but worry about how it looks on mobile. Likewise, it could be that most of our downloads + usage is from US/EUR/CAN/AUS. It opens doors to us. If we get popular in other slower internet speeds countries, we then can accommodate (just like what we do with web).

**Comment by ahmedre** [comment]
strongly agree - cc @mohamede1945 who may know these stats

**Comment by mohamede1945** [comment]
https://drive.google.com/open?id=0B6QDEdDTqWk3bkY1OUJsVFkzeU0

**Comment by mmahalwy** [comment]
Oh wow. how are we so big in Malaysia?

**Comment by mohamede1945** [comment]
No idea! But we are not big so 1.3K is not so indicative number. I think the only thing these data tells us is that we still lack main features and the app should be on a par with the Android app.

**Comment by abdelouali** [comment]
Yeah, i think also it needs to par the android app. If you look at the
android app 10mil downloads incredible.

But inshaAllah the ios app will achieve that target one day.

Op 13 nov. 2016 21:00 schreef "Mohamed Afifi" <notifications@github.com>:

**Comment by mohamede1945** [comment]
I think we are following the Android with that regard.
