### ISSUE TITLE
Download Quran Images On Startup

### ISSUE THREAD

**Issue by mohamede1945** [quran/quran-ios#7]
- [ ] When the app loaded check if it's the first time, then download the quran images.
- [ ] Save the images on disk on the documents directory.
- [ ] Unzip the images file, delete the zip file.
- [ ] Save images version locally.
- [ ] If the version changes on a new app update/install, delete existing images and re-download them again.
- [ ] Make sure the app starts as fast as possible. Checking if the images downloaded or not shouldn't exceed few milliseconds (e.g. don't go through all the downloaded images and check if they exist or not).

**Comment by ahmedre** [comment]
imho, it's better to include the images with the app on iOS - for Android, we did the "download images" route for two reasons - 1. back when we started, there was a limit on the size of an apk (it was ~50mb, the images were bigger than that), 2. i thought it made a big difference to load images specific to the screen size, but this isn't the case (Android and iOS do a fairly great job of scaling images up and down).

moreover, i think internet connectivity is a little less of an issue for iOS than it is for Android (since people who can afford an iOS device likely have access to internet as well). so i recommend not doing this and deciding on either bundling one or two image sizes with the app (depending on whether you need a separate size to handle iPads).

**Comment by ahmedre** [comment]
on the flip side, the downside of the approach of bundling images is that it's hard to switch to another image set in the future (without publishing flavors of the app, for example). however, this all comes down to whether or not we can come up with a good way of telling people, "which Quran style do you want?" - this is more difficult than it seems (it's not just a ux issue, but also an explanation issue - you'd be surprised at the number of people who download our Qaloon app because they like how the pages look, then give us a low star rating because of "mistakes" relative to Hafs that they're used to, for example).

**Comment by mohamede1945** [comment]
I totally agree with you. Actually, now apple does App Thinning for devices running iOS 9+ which will benefit us if we bundled more than 1 image set.
