### ISSUE TITLE
React-Native hybrid

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran-ios#75]
Salam all,

Want to get your opinion on this. Airbnb has a wonderful iOS app (and I think their Android too) that is a mix of native and React-Native. Coincidently, quran.com is built on React. Thus, my suggestion is, what if we follow those footsteps of having a hybrid between the two. Perhaps all the online stuff can be React Native.

Thoughts?

CC: @mohamede1945 @ahmedre

**Comment by mohamede1945** [comment]
I agree with you since it will save us consuming the new services twice just once and share the code between the 2 platforms. I would gladly help with integration between the React-Native and the Native code (if needed). 

My main question would be how many people interested in participating and the experience they have?

**Comment by mmahalwy** [comment]
CC @sabeur about this. I certainly am. That being said, I don't know if it will be worth it if we get moving more on ios. It might be better for you guys to handle it. But, if we predict some slowdown on the ios end of things, then having React-Native and the quran.com team help might be worth it!

**Comment by jayhub** [comment]
I personally don't feel react would provide the same user experience as native. Just saying.

**Comment by abunur** [comment]
I don't agree with incorporating React-Native, either.  For Quran.com services there should be no need to utilize this in order to consume the API.  Furthermore would add unnecessary complexity to an app that is already fully native.
